"""org_id nullable set to false

Revision ID: 66b21269d33c
Revises: a6c0798885e2
Create Date: 2026-08-27 13:57:17.342600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b21269d33c'
down_revision: Union[str, None] = 'a6c0798885e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
