"""organization table and role table included

Revision ID: a6c0798885e2
Revises: e110db973657
Create Date: 2026-08-27 13:26:19.350424

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a6c0798885e2'
down_revision: Union[str, None] = 'e110db973657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_uid'), 'organizations', ['uid'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(), server_default= 'user', nullable=False))
    op.add_column('users', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'organization_id')
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_organizations_uid'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
